name: PyInstaller

on: [workflow_dispatch, push]

jobs:
  windows:
    name: 'Windows'
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.1'
        architecture: 'x86'
        cache: 'pip'

    - name: Install requirements and PyInstaller
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Run PyInstaller
      run: |
        pyinstaller main.py -F -n csrpc

    - name: Deploy Artifact
      uses: actions/upload-artifact@v2
      with:
        name: win32
        path: dist

  linux:
    name: 'Linux'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.1'
        architecture: 'x64'
        cache: 'pip'

    - name: Install requirements and PyInstaller
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Run PyInstaller
      run: |
        pyinstaller main.py -F -n csrpc

    - name: Deploy Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: dist

  darwin:
    name: 'Darwin'
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.1'
        architecture: 'x64'
        cache: 'pip'

    - name: Install requirements and PyInstaller
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Run PyInstaller
      run: |
        pyinstaller main.py -F -n csrpc

    - name: Deploy Artifact
      uses: actions/upload-artifact@v2
      with:
        name: darwin
        path: dist
